=== yoyz/linux/ipalloc-python/example/ip_allocation.dtd
<!ELEMENT ip_allocation (network)*> 

<!ELEMENT network (logical_network)*> 
<!ATTLIST  network 
   name CDATA #REQUIRED 
   function (bb|mn|ic|nfs|serial|power|other) #REQUIRED
   techno CDATA #IMPLIED
> 

<!ELEMENT logical_network ((member| range)*)> 
<!ATTLIST  logical_network 
    name CDATA #REQUIRED
    type (primary|secondary) #IMPLIED
    function (bb|mn|ic|nfs|serial|power|other) #IMPLIED
    subnet CDATA #REQUIRED
    gateway CDATA #IMPLIED
    vlan_id CDATA #IMPLIED
    pkey CDATA #IMPLIED
> 
<!ELEMENT range (member)*> 
<!ATTLIST  range 
    first_ip CDATA #REQUIRED 
>  
<!ELEMENT member EMPTY> 
<!ATTLIST  member 
    object (node|switch|hwmanager|disk_array|metaservice) #IMPLIED 
    type CDATA #IMPLIED
    group CDATA #IMPLIED 
    interface_name CDATA #IMPLIED 
    logical_interface_name CDATA #IMPLIED 
>

=== yoyz/linux/ipalloc-python/example/example_two_management_and_secondary_ib_network.xml
<!DOCTYPE ip_allocation SYSTEM "ip_allocation.dtd">
<ip_allocation>
<network name="admin" function="mn">

  <logical_network name="admin" type="primary" subnet="10.0.32.0/23" gateway="10.0.33.254" vlan_id="32" >
    <range first_ip="10.0.32.1" >
      <member object="node" type="mngt" group="Service" />
      <member object="node" type="mws" group="Service" />
    </range>
    <range first_ip="10.0.32.181" >
      <member object="metaservice" type="alias" />
    </range>
    <range first_ip="10.0.32.201" >
      <member object="metaservice" type="mvm" />
    </range>
 </logical_network>

  <logical_network name="compute"  type="primary" subnet="10.1.32.0/23" gateway="10.1.33.254" vlan_id="31" >
    <range first_ip="10.1.32.121" >
      <member object="node" type="compute" group="Compute" />
    </range>
  </logical_network>









<network name="interconnect" function="ic">

  <logical_network name="interconnect"  type="primary" subnet="10.2.0.0/16" gateway="10.2.255.254" pkey="FFFF" >
    <range first_ip="10.2.32.1" >
      <member object="node" type="mngt" group="Service" />
      <member object="node" type="mws" group="Service" />
    </range>
    <range first_ip="10.2.32.7" >
      <member object="node" type="mds" group="Service" interface_name="ib0" />
    </range>
    <range first_ip="10.2.33.7" >
      <member object="node" type="mds" group="Service" interface_name="ib1" />
    </range>
    <range first_ip="10.2.32.121" >
      <member object="node" type="compute" group="Compute" />
    </range>
 </logical_network>

  <logical_network name="backbone"  type="secondary" subnet="14.1.32.0/23" gateway="14.1.33.254" pkey="8132" >
    <range first_ip="14.1.32.1" >
      <member object="node" type="mngt" group="Service" />
      <member object="node" type="mws" group="Service" />
    </range>
    <range first_ip="14.1.32.7" >
      <member object="node" type="io" group="Service" />
    </range>
    <range first_ip="14.1.32.121" >
      <member object="node" type="compute" group="Compute" />
    </range>
    <range first_ip="14.1.33.231" >
      <member object="node" type="nfs"/>
    </range>
  </logical_network>
</network>

=== yoyz/linux/ipalloc-python/example/demo.xml
<!DOCTYPE ip_allocation SYSTEM "ip_allocation.dtd">
 <ip_allocation>

  <network name="admin" function="mn">
   <logical_network name="admin" type="primary" subnet="10.11.0.0/16" gateway="10.11.255.254">
    <range first_ip="10.11.0.1" >
     <member object="node" type="mngt"/>
     <member object="node" type="mws"/>
     <member object="node" type="io"/>
     <member object="node" type="nfs"/>
     <member object="node" type="mds"/>
     <member object="node" type="oss"/>
     <member object="metaservice" type="alias"/>
     <member object="metaservice" type="vm"/>
   </range>
   <range first_ip="10.11.1.1" >
    <member object="node" type="compute"/>
   </range>
   <range first_ip="10.11.100.1" >
    <member object="hwmanager" type="bmc[mngt]"/>
    <member object="hwmanager" type="bmc[mws]"/>
    <member object="hwmanager" type="bmc[io]"/>
    <member object="hwmanager" type="bmc[nfs]"/>
    <member object="hwmanager" type="bmc[mds]"/>
    <member object="hwmanager" type="bmc[oss]"/>
   </range>
   <range first_ip="10.11.101.1" >
    <member object="hwmanager" type="bmc[compute]"/>
    <member object="hwmanager" type="cmc"/>
   </range>
   <range first_ip="10.11.200.1" >
    <member object="switch"/>
   </range>
   <range first_ip="10.11.201.1" >
    <member object="hwmanager" type="coldoor"/>
   </range>
   <range first_ip="10.11.202.1" >
    <member object="disk_array"/>
   </range>
  </logical_network>
 </network>

 <network name="backbone" function="bb">
  <logical_network name="backbone" type="primary" subnet="20.11.0.0/16" gateway="20.11.255.254" suffix="bone">
   <range first_ip="20.11.0.10" >
<!-- <member object="node" type="mngt"/> -->
<!-- <member object="node" type="mws"/> -->
    <member object="node" type="io"/>
    <member object="node" type="nfs"/>
    <member object="metaservice" type="alias"/>
    <member object="metaservice" type="vm"/>
   </range>
   <range first_ip="20.11.1.1" >
    <member object="node" type="compute"/>
   </range>
   <range first_ip="20.11.100.1" >
    <member object="hwmanager" type="bmc[mngt]"/>
    <member object="hwmanager" type="bmc[mws]"/>
    <member object="hwmanager" type="bmc[io]"/>
    <member object="hwmanager" type="bmc[nfs]"/>
    <member object="hwmanager" type="bmc[mds]"/>
    <member object="hwmanager" type="bmc[oss]"/>
   </range>
   <range first_ip="20.11.101.1" >
    <member object="hwmanager" type="bmc[compute]"/>
   </range>
   <range first_ip="20.11.200.1" >
    <member object="switch"/>
   </range>
  </logical_network>
 </network>



<network name="interconnect" function="ic">
 <logical_network name="interconnect" type="primary" subnet="10.12.0.0/16" gateway="10.12.255.254" suffix="ib0">
  <range first_ip="10.12.0.1" >
   <member object="node" type="mngt" interface_name="ib0"/>
   <member object="node" type="mws"  interface_name="ib0"/>
   <member object="node" type="io"   interface_name="ib0"/>
   <member object="node" type="nfs"  interface_name="ib0"/>
   <member object="node" type="mds"  interface_name="ib0"/>
   <member object="node" type="oss"  interface_name="ib0"/>
  </range>

  <range first_ip="10.12.1.1" >
   <member object="node" type="compute" interface_name="ib0"/>
  </range>

  <range first_ip="10.12.200.1" >
   <member object="switch"/>
  </range>
 </logical_network>


 <logical_network name="interconnect2" type="primary" subnet="10.13.0.0/16" gateway="10.13.255.254" suffix="ib1">
  <range first_ip="10.13.0.1" >
   <member object="node" type="mngt" interface_name="ib1"/>
   <member object="node" type="mws"  interface_name="ib1"/>
   <member object="node" type="io"   interface_name="ib1"/>
   <member object="node" type="nfs"  interface_name="ib1"/>
   <member object="node" type="mds"  interface_name="ib1"/>
   <member object="node" type="oss"  interface_name="ib1"/>
  </range>
  <range first_ip="10.13.1.1" >
   <member object="node" type="compute" interface_name="ib1"/>
  </range>
 </logical_network> 
</network>


</ip_allocation>

=== yoyz/linux/ipalloc-python/example/netmap-extend-demo-phase1.xml
<!DOCTYPE ip_allocation SYSTEM "ip_allocation.dtd">
<ip_allocation>

<!--
Some parts of this network map are comments.
These parts will be useful later, to perform an extension:
 - uncomment them ;
 - then apply again your network map.
-->

<network name="admin" function="mn">
	<logical_network name="admin" type="primary" subnet="172.16.0.0/16" >
		<range first_ip="172.16.0.1" >
			<member object="node" type="mngt" />
			<member object="node" type="mws" />
			<member object="node" type="login" />
			<member object="node" type="io" />
		</range>
		<range first_ip="172.16.0.100" >
			<member object="metaservice" type="vmgeneric"/>
			<member object="metaservice" type="vm"/>
			<member object="metaservice" type="alias"/>
		</range>
		<range first_ip="172.16.1.1" >
			<member object="hwmanager" type="bmc[mngt]"/>
			<member object="hwmanager" type="bmc[mws]"/>
			<member object="hwmanager" type="bmc[login]"/>
			<member object="hwmanager" type="bmc[io]"/>
		</range>
		<range first_ip="172.16.10.1" >
			<member object="node" type="compute"/>
		</range>
		<range first_ip="172.16.20.1" >
			<member object="hwmanager" type="bmc[compute]"/>
		</range>
		<range first_ip="172.16.30.1" >
			<member object="hwmanager" type="cmc"/>
		</range>
		<range first_ip="172.16.100.1" >
			<member object="switch" type="eth" />
			<member object="switch" type="talim" />
		</range>
		<range first_ip="172.16.110.1" >
			<member object="disk_array"/>
		</range>
 </logical_network>
</network>

<network name="interconnect1" function="ic">
	<logical_network name="interconnect1"	type="primary" subnet="172.17.0.0/16" suffix="ic1" >
		<range first_ip="172.17.0.1" >
			<member object="node" type="mngt" interface_name="ib0" />
			<member object="node" type="mws" interface_name="ib0" />
			<member object="node" type="login" interface_name="ib0" />
			<member object="node" type="io" interface_name="ib0" />
		</range>
		<range first_ip="172.17.10.1" >
			<member object="node" type="compute" interface_name="ib0" />
		</range>
	</logical_network>
</network>

<!--
Extension 1: you need to add a 2nd interconnect network.
Note: the primary network "interconnect2" has to be defined 
in your preload at first.
-->
<!--
<network name="interconnect2" function="ic">
	<logical_network name="interconnect2"	type="primary" subnet="172.18.0.0/16" suffix="ic2" >
		<range first_ip="172.18.0.1" >
			<member object="node" type="io" interface_name="ib1" />
		</range>
		<range first_ip="172.18.10.1" >
			<member object="node" type="compute" interface_name="ib1" />
		</range>
	</logical_network>
</network>
-->

<network name="backbone" function="bb">
	<logical_network name="backbone"	type="primary" subnet="10.0.0.0/16" gateway="10.0.0.1" suffix="bb" >
		<range first_ip="10.0.0.1" >
			<member object="node" type="mngt" />
			<member object="node" type="mws" />
			<member object="node" type="login" />
			<member object="node" type="io" />
		</range>

		<!--
		Extension 2: you "forgot" to define your metaservice aliases on 
		the backbone network.
		-->
		<!--
		<range first_ip="10.0.0.100" >
			<member object="metaservice" type="alias"/>
		</range>
		-->

		<range first_ip="10.0.10.1" >
			<member object="node" type="compute"/>
		</range>
		<range first_ip="10.0.100.1" >
			<member object="switch" type="eth" />
		</range>
	</logical_network>
</network>

</ip_allocation>

=== yoyz/linux/ipalloc-python/example/example_one_management_network.xml
<!DOCTYPE ip_allocation SYSTEM "ip_allocation.dtd">

 <ip_allocation>
 <network name="admin" function="mn">
  <logical_network name="admin" type="primary" subnet="10.5.0.0/16" gateway="10.5.255.254">
    <range first_ip="10.5.0.1" >
      <member object="node" type="mngt"/>
    </range>
    <range first_ip="10.5.1.1" >
      <member object="node" type="compute"/>
    </range>
    <range first_ip="10.5.100.1" >
      <member object="hwmanager" type="bmc[mngt]"/>
    </range>
    <range first_ip="10.5.101.1" >
      <member object="hwmanager" type="bmc[compute]"/>
    </range>
    <range first_ip="10.5.200.1" >
      <member object="switch"/>
    </range>
  </logical_network>
  </network>
 </ip_allocation>

=== yoyz/linux/ipalloc-python/example/system_test.xml
<!DOCTYPE ip_allocation SYSTEM "ip_allocation.dtd">

<ip_allocation>
<!-- Tera100 system test -->

<!-- ****************** -->
<!--   admin networks   -->
<!-- ****************** -->

<!-- admin network -->
<network name="admin" function="mn">
  <logical_network name="admin" type="primary" subnet="A1.B1.88.0/23" gateway="A1.B1.89.254" vlan_id="188" >
    <range first_ip="A1.B1.88.1" >
      <member object="node" type="mngt"/>
    </range>
 </logical_network>

<!-- compute network -->
  <logical_network name="compute"  type="primary" subnet="A2.B2.88.0/23" gateway="A2.B2.89.254" vlan_id="188" >
    <range first_ip="A2.B2.88.21" >
      <member object="node" type="compute"/>
    </range>
  </logical_network>

<!-- io network -->
  <logical_network name="io"  type="primary" subnet="A3.B3.88.0/23" gateway="A3.B3.89.254" vlan_id="188" >
    <range first_ip="A3.B3.88.3" >
      <member object="node" type="io" />
      <member object="node" type="mds" />
      <member object="node" type="router"/>
    </range>
  </logical_network>

<!-- equipment network -->
  <logical_network name="equipement"  type="primary" subnet="A4.B4.88.0/23" gateway="A4.B4.89.254" vlan_id="188" >
    <range first_ip="A4.B4.88.1" >
      <member object="hwmanager" type="bmc[mngt]" />
    </range>
    <range first_ip="A4.B4.88.3" >
      <member object="hwmanager" type="bmc[io]" />
      <member object="hwmanager" type="bmc[mds]"/>
      <member object="hwmanager" type="bmc[router]" />
    </range>
    <range first_ip="A4.B4.88.21" >
      <member object="hwmanager" type="bmc[compute]"/>
    </range>
    <range first_ip="A4.B4.89.151" >
      <member object="switch" />
    </range>
    <range first_ip="A4.B4.89.171" >
      <member object="hwmanager" type="coldoor" />
      <member object="disk_array"/>
    </range>
  </logical_network>
</network>
<!-- ************************* -->
<!--   interconnect networks   -->
<!-- ************************* -->

<!-- ib_admin network -->
<network name="interconnect" function="ic">
  <logical_network name="interconnect"  type="primary" subnet="A5.B5.0.0/16" gateway="A5.B5.255.254" pkey="FFFF" >
    <range first_ip="A5.B5.88.1" >
      <member object="node" type="mngt" />
    </range>
    <range first_ip="A5.B5.88.3" >
      <member object="node" type="io" interface_name="ib0"/>
      <member object="node" type="mds" interface_name="ib0"/>
      <member object="node" type="router" interface_name="ib0"/>
    </range>
<!--    <range first_ip="A5.B5.88.3" >
      <member object="node" type="io"  interface_name="ib1"/>
      <member object="node" type="mds"  interface_name="ib1"/>
      <member object="node" type="router" interface_name="ib1"/>
    </range> -->
    <range first_ip="A5.B5.88.21" >
      <member object="node" type="compute" />
    </range>
  </logical_network>

<!-- ib_backbone network -->

  <logical_network name="ib_backbone"  type="secondary" subnet="A6.B6.88.0/23" gateway="A6.B6.89.254" pkey="8188" >
    <range first_ip="A6.B6.88.1" >
      <member object="node" type="mngt" />
    </range>
    <range first_ip="A6.B6.88.3" >
      <member object="node" type="io" />
      <member object="node" type="mds"/>
      <member object="node" type="router"/>
    </range>
    <range first_ip="A6.B6.88.21" >
      <member object="node" type="compute"/>
    </range>
  </logical_network>
</network>
</ip_allocation>

=== yoyz/linux/ipalloc-python/example/allocation_sample_staging.xml
<!DOCTYPE ip_allocation SYSTEM "ip_allocation.dtd">

<ip_allocation>
<!-- Stagging CLM -->

<!-- ****************** -->
<!--   admin networks   -->
<!-- ****************** -->

<!-- admin network -->
<network name="admin" function="mn">
  <logical_network name="admin" type="primary" subnet="11.1.88.0/23" gateway="11.1.89.254" vlan_id="188" >
    <range first_ip="11.1.88.1" >
      <member object="node" type="mngt"/>
      <member object="node" type="msw"/>
    </range>
    <range first_ip="11.1.88.21" >
      <member object="metaservice" type="vm"/>
      <member object="metaservice" type="alias"/>
    </range>
 </logical_network>

<!-- compute network -->
  <logical_network name="compute"  type="primary" subnet="11.2.88.0/23" gateway="11.2.89.254" vlan_id="188" >
    <range first_ip="11.2.88.101" >
      <member object="node" type="compute"/>
    </range>
    <range first_ip="11.2.89.221" >
      <member object="node" type="router" />
    </range>
  </logical_network>

<!-- io network -->
  <logical_network name="io"  type="primary" subnet="11.3.88.0/23" gateway="11.3.89.254" vlan_id="188" >
    <range first_ip="11.3.88.3" >
      <member object="node" type="io" />
      <member object="node" type="mds" />
    </range>
  </logical_network>

<!-- equipment network -->
  <logical_network name="equipement"  type="primary" subnet="11.4.88.0/23" gateway="11.4.89.254" vlan_id="188" >
    <range first_ip="11.4.88.1" >
      <member object="hwmanager" type="bmc[mngt]" />
      <member object="hwmanager" type="bmc[mws]" />
    </range>
    <range first_ip="11.4.88.3" >
      <member object="hwmanager" type="bmc[io]" />
      <member object="hwmanager" type="bmc[mds]"/>
    </range>
    <range first_ip="11.4.88.101" >
      <member object="hwmanager" type="bmc[compute]"/>
    </range>
    <range first_ip="11.4.89.151" >
      <member object="switch" />
    </range>
    <range first_ip="11.4.89.171" >
      <member object="hwmanager" type="coldoor" />
      <member object="disk_array"/>
    </range>
    <range first_ip="11.4.89.221" >
      <member object="hwmanager" type="bmc[router]" />
    </range>
  </logical_network>
</network>
<!-- ************************* -->
<!--   interconnect networks   -->
<!-- ************************* -->

<!-- ib_admin network -->
<network name="interconnect" function="ic">
  <logical_network name="interconnect"  type="primary" subnet="12.1.0.0/16" gateway="12.1.255.254" pkey="FFFF" >
    <range first_ip="12.1.88.1" >
      <member object="node" type="mngt" />
    </range>
    <range first_ip="12.1.88.3" >
      <member object="node" type="io" interface_name="ib0"/>
      <member object="node" type="mds" interface_name="ib0"/>
    </range>
    <range first_ip="12.1.88.21" >
      <member object="metaservice" type="vm" />
      <member object="metaservice" type="alias" />
    </range>
    <range first_ip="12.1.88.101" >
      <member object="node" type="compute" />
    </range>
    <range first_ip="12.1.89.221" >
      <member object="node" type="router" />
    </range>
   </logical_network>

<!-- ib_backbone network -->

  <logical_network name="ib_backbone"  type="secondary" subnet="12.2.88.0/23" gateway="12.2.89.254" pkey="8188" >
    <range first_ip="12.2.88.1" >
      <member object="node" type="mngt" />
    </range>
    <range first_ip="12.2.88.3" >
      <member object="node" type="io" />
      <member object="node" type="mds"/>
    </range>
    <range first_ip="12.2.88.21" >
      <member object="metaservice" type="vm" />
      <member object="metaservice" type="alias" />
    </range>
    <range first_ip="12.2.88.101" >
      <member object="node" type="compute"/>
    </range>
    <range first_ip="12.2.89.221" >
      <member object="node" type="router" />
    </range>
  </logical_network>
</network>
</ip_allocation>
You have new mail in /var/spool/mail/root
[root@tamago1 ~]# cat /usr/lib/clustmngt/clusterdb/install/staggingclm.xml
<!DOCTYPE ip_allocation SYSTEM "ip_allocation.dtd">

<ip_allocation>
<!-- Stagging CLM -->

<!-- ****************** -->
<!--   admin networks   -->
<!-- ****************** -->

<!-- admin network -->
<network name="admin" function="mn">
  <logical_network name="admin" type="primary" subnet="11.1.88.0/23" gateway="11.1.89.254" vlan_id="188" >
    <range first_ip="11.1.88.1" >
      <member object="node" type="mngt"/>
      <member object="node" type="msw"/>
    </range>
    <range first_ip="11.1.88.21" >
      <member object="metaservice" type="vm"/>
      <member object="metaservice" type="alias"/>
    </range>
 </logical_network>

<!-- compute network -->
  <logical_network name="compute"  type="primary" subnet="11.2.88.0/23" gateway="11.2.89.254" vlan_id="188" >
    <range first_ip="11.2.88.101" >
      <member object="node" type="compute"/>
    </range>
    <range first_ip="11.2.89.221" >
      <member object="node" type="router" />
    </range>
  </logical_network>

<!-- io network -->
  <logical_network name="io"  type="primary" subnet="11.3.88.0/23" gateway="11.3.89.254" vlan_id="188" >
    <range first_ip="11.3.88.3" >
      <member object="node" type="io" />
      <member object="node" type="mds" />
    </range>
  </logical_network>

<!-- equipment network -->
  <logical_network name="equipement"  type="primary" subnet="11.4.88.0/23" gateway="11.4.89.254" vlan_id="188" >
    <range first_ip="11.4.88.1" >
      <member object="hwmanager" type="bmc[mngt]" />
      <member object="hwmanager" type="bmc[mws]" />
    </range>
    <range first_ip="11.4.88.3" >
      <member object="hwmanager" type="bmc[io]" />
      <member object="hwmanager" type="bmc[mds]"/>
    </range>
    <range first_ip="11.4.88.101" >
      <member object="hwmanager" type="bmc[compute]"/>
    </range>
    <range first_ip="11.4.89.151" >
      <member object="switch" />
    </range>
    <range first_ip="11.4.89.171" >
      <member object="hwmanager" type="coldoor" />
      <member object="disk_array"/>
    </range>
    <range first_ip="11.4.89.221" >
      <member object="hwmanager" type="bmc[router]" />
    </range>
  </logical_network>
</network>
<!-- ************************* -->
<!--   interconnect networks   -->
<!-- ************************* -->

<!-- ib_admin network -->
<network name="interconnect" function="ic">
  <logical_network name="interconnect"  type="primary" subnet="12.1.0.0/16" gateway="12.1.255.254" pkey="FFFF" >
    <range first_ip="12.1.88.1" >
      <member object="node" type="mngt" />
    </range>
    <range first_ip="12.1.88.3" >
      <member object="node" type="io" interface_name="ib0"/>
      <member object="node" type="mds" interface_name="ib0"/>
    </range>
    <range first_ip="12.1.88.21" >
      <member object="metaservice" type="vm" />
      <member object="metaservice" type="alias" />
    </range>
    <range first_ip="12.1.88.101" >
      <member object="node" type="compute" />
    </range>
    <range first_ip="12.1.89.221" >
      <member object="node" type="router" />
    </range>
   </logical_network>

<!-- ib_backbone network -->

  <logical_network name="ib_backbone"  type="secondary" subnet="12.2.88.0/23" gateway="12.2.89.254" pkey="8188" >
    <range first_ip="12.2.88.1" >
      <member object="node" type="mngt" />
    </range>
    <range first_ip="12.2.88.3" >
      <member object="node" type="io" />
      <member object="node" type="mds"/>
    </range>
    <range first_ip="12.2.88.21" >
      <member object="metaservice" type="vm" />
      <member object="metaservice" type="alias" />
    </range>
    <range first_ip="12.2.88.101" >
      <member object="node" type="compute"/>
    </range>
    <range first_ip="12.2.89.221" >
      <member object="node" type="router" />
    </range>
  </logical_network>
</network>
</ip_allocation>
